/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import javax.swing.JOptionPane;
import controle.ConectaBanco;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alexandre
 */
public class Principal extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2calc = new javax.swing.JMenuItem();
        jMenuItemNotepad = new javax.swing.JMenuItem();
        jMenu4Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Cadastro");

        jMenu1.setText("Cadastro");

        jMenuItem1.setText("Cadastro de Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilitários");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2calc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2calc.setText("Calculadora");
        jMenuItem2calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2calcActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2calc);

        jMenuItemNotepad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemNotepad.setText("Bloco de Notas");
        jMenuItemNotepad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotepadActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNotepad);

        jMenuBar1.add(jMenu2);

        jMenu4Sair.setText("Sair");
        jMenu4Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4SairMouseClicked(evt);
            }
        });
        jMenu4Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4SairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(696, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4SairMouseClicked
       
        
        

switch (JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema ?")) {  
            case 0:  
                System.out.println("botao yes clicado");
                System.exit(0);
                conecta.desconecta();
                break;  
            case 1:  
                System.out.println("botao no clicado");  
                break;  
            case 2:  
                System.out.println("botao cancel clicado");  
                break;}

// TODO add your handling code here:
        //System.exit(0);
        
    }//GEN-LAST:event_jMenu4SairMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
FrmCadastrodeClientes frm = new FrmCadastrodeClientes();
        frm.setVisible(true);        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2calcActionPerformed
try {
            Runtime.getRuntime().exec("calc");
            
            
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
                                             
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2calcActionPerformed

    private void jMenu4SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4SairActionPerformed
switch (JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema ?")) {  
            case 0:  
                System.out.println("botao yes clicado");
                System.exit(0);
                conecta.desconecta();
                break;  
            case 1:  
                System.out.println("botao no clicado");  
                break;  
            case 2:  
                System.out.println("botao cancel clicado");  
                break;} 
        
        
    
        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu4SairActionPerformed

    private void jMenuItemNotepadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotepadActionPerformed
try {
            Runtime.getRuntime().exec("notepad");
            
            
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
                          // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNotepadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4Sair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2calc;
    private javax.swing.JMenuItem jMenuItemNotepad;
    // End of variables declaration//GEN-END:variables
}
